### PR TITLE
feat: Extensible step kinds via service locator pattern

### PR DESCRIPTION
**Pull request by jimmidyson**
This PR is a merge of funktionio/funktion-connectors#222 that makes more sense for Syndesis than it did for the original project.

I'd like to merge this ASAP so I can work on connector triggers in the runtime.

### CODE REVIEW

**Review by zregvart — DISMISSED** [review]
👍

**Comment by jimmidyson** [comment]
Hold off merging please - seen some stuff that needs updating... sorry! Dismissing PR review.

**Comment by zregvart** [comment]
TBH I would prefer two PRs one for the Service loading other for the new Step implementations added.

**Comment by jimmidyson** [comment]
I don't think this adds any new step implementations, just refactors existing step implementations to the new service loader mechanism. But it's been a long time since I did this originally and I could be wrong or misunderstanding what you mean - can you point out what you mean please?

**Comment by zregvart** [comment]
@jimmidyson from the diff at least it looks like `io.syndesis.integration.runtime.stephandlers` is a new package, I have misunderstood those for new steps, its part of the Service loader implementation, right?

**Comment by jimmidyson** [comment]
Yeah they are the extracted steps which were hard coded in the old route builder, no new functionality added, as you can see from the fact that tests were not updated, just simply refactoring.

**Comment by jimmidyson** [comment]
I decided to leave functionality as-is right now so this is simply a refactoring rather than changes to logic, which will happen in subsequent PRs. @zregvart If you want to re-review and approve, would be appreciated.

**Review by zregvart — APPROVED** [review]
👍

**Comment by jimmidyson** [comment]
Thanks @zregvart!

**Pull request merged**
